name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - libspatialindex
  - matplotlib
  - rtree
  - seaborn
  - splot
  - watermark
  - pip
  - pip:
    - git+https://github.com/pysal/giddy.git@main
